/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import controller.ChatPanelController;
import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.JTextPane;

/**
 *
 * @author Camilo
 */
public class ChatPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChatPanel
     */
    public ChatPanel() {
        initComponents();
        ChatPanelController.load(this);
    }

    public JButton getjBSend() {
        return jBSend;
    }

    public JTextField getjTFInput() {
        return jTFInput;
    }

    public JTextPane getjTPTerminal() {
        return jTPTerminal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPCenter = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTPTerminal = new javax.swing.JTextPane();
        jTFInput = new javax.swing.JTextField();
        jBSend = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(jTPTerminal);

        jTFInput.setText("jTextField1");

        jBSend.setText("jButton1");
        jBSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPCenterLayout = new javax.swing.GroupLayout(jPCenter);
        jPCenter.setLayout(jPCenterLayout);
        jPCenterLayout.setHorizontalGroup(
            jPCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPCenterLayout.createSequentialGroup()
                        .addComponent(jTFInput, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBSend)))
                .addContainerGap())
        );
        jPCenterLayout.setVerticalGroup(
            jPCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFInput)
                    .addComponent(jBSend, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addContainerGap())
        );

        add(jPCenter, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jBSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSendActionPerformed
        //
    }//GEN-LAST:event_jBSendActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBSend;
    private javax.swing.JPanel jPCenter;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFInput;
    private javax.swing.JTextPane jTPTerminal;
    // End of variables declaration//GEN-END:variables
}
