/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.TableroViewController;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;


/**
 *
 * @author Ramiro
 */
public class TableroView extends javax.swing.JFrame {
    /**
     * Creates new form TableroView
     */
    public TableroView() {
        initComponents();
        TableroViewController.load(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Playeract = new javax.swing.JLabel();
        Panel_Center = new javax.swing.JPanel();
        Panel_Tablero = new javax.swing.JPanel();
        Label_P1 = new javax.swing.JLabel();
        Label_P2 = new javax.swing.JLabel();
        Label_P3 = new javax.swing.JLabel();
        Label_P4 = new javax.swing.JLabel();
        Label_Tablero = new javax.swing.JLabel();
        Label_CGO = new javax.swing.JPanel();
        Label_CJail = new javax.swing.JPanel();
        Label_CFree = new javax.swing.JPanel();
        Label_CGoto = new javax.swing.JPanel();
        Panel_Left = new javax.swing.JPanel();
        Panel_Information = new javax.swing.JPanel();
        Panel_PlayerInfo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Label_Dado1 = new javax.swing.JLabel();
        Label_Dado2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Button_Throw = new javax.swing.JButton();
        Turno_lbl = new javax.swing.JLabel();
        NameC_lbl = new javax.swing.JLabel();
        Panel_Players = new javax.swing.JPanel();
        PanelP1 = new javax.swing.JPanel();
        NameP1 = new javax.swing.JLabel();
        LastP1 = new javax.swing.JLabel();
        BalP1 = new javax.swing.JLabel();
        PanelP2 = new javax.swing.JPanel();
        NameP2 = new javax.swing.JLabel();
        LastP2 = new javax.swing.JLabel();
        BalP2 = new javax.swing.JLabel();
        PanelP3 = new javax.swing.JPanel();
        NameP3 = new javax.swing.JLabel();
        LastP3 = new javax.swing.JLabel();
        BalP3 = new javax.swing.JLabel();
        PanelP4 = new javax.swing.JPanel();
        NameP4 = new javax.swing.JLabel();
        LastP4 = new javax.swing.JLabel();
        BalP4 = new javax.swing.JLabel();
        Panel_ChatContainer = new javax.swing.JPanel();

        Playeract.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        Panel_Center.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Center.setPreferredSize(new java.awt.Dimension(650, 700));

        Panel_Tablero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Panel_Tablero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_P1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/carr.png"))); // NOI18N
        Panel_Tablero.add(Label_P1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 40, 30));

        Label_P2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/hat.png"))); // NOI18N
        Panel_Tablero.add(Label_P2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 40, 30));

        Label_P3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/dog.png"))); // NOI18N
        Panel_Tablero.add(Label_P3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 40, 30));

        Label_P4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/dedal.png"))); // NOI18N
        Panel_Tablero.add(Label_P4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 30, -1));

        Label_Tablero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/tabmonpoly.png"))); // NOI18N
        Panel_Tablero.add(Label_Tablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout Label_CGOLayout = new javax.swing.GroupLayout(Label_CGO);
        Label_CGO.setLayout(Label_CGOLayout);
        Label_CGOLayout.setHorizontalGroup(
            Label_CGOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        Label_CGOLayout.setVerticalGroup(
            Label_CGOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Panel_Tablero.add(Label_CGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 90, 90));

        javax.swing.GroupLayout Label_CJailLayout = new javax.swing.GroupLayout(Label_CJail);
        Label_CJail.setLayout(Label_CJailLayout);
        Label_CJailLayout.setHorizontalGroup(
            Label_CJailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        Label_CJailLayout.setVerticalGroup(
            Label_CJailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Panel_Tablero.add(Label_CJail, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 560, 90, 90));

        javax.swing.GroupLayout Label_CFreeLayout = new javax.swing.GroupLayout(Label_CFree);
        Label_CFree.setLayout(Label_CFreeLayout);
        Label_CFreeLayout.setHorizontalGroup(
            Label_CFreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        Label_CFreeLayout.setVerticalGroup(
            Label_CFreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Panel_Tablero.add(Label_CFree, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 90, 90));

        javax.swing.GroupLayout Label_CGotoLayout = new javax.swing.GroupLayout(Label_CGoto);
        Label_CGoto.setLayout(Label_CGotoLayout);
        Label_CGotoLayout.setHorizontalGroup(
            Label_CGotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        Label_CGotoLayout.setVerticalGroup(
            Label_CGotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        Panel_Tablero.add(Label_CGoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 90));

        javax.swing.GroupLayout Panel_CenterLayout = new javax.swing.GroupLayout(Panel_Center);
        Panel_Center.setLayout(Panel_CenterLayout);
        Panel_CenterLayout.setHorizontalGroup(
            Panel_CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(Panel_CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Panel_CenterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Panel_Tablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        Panel_CenterLayout.setVerticalGroup(
            Panel_CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(Panel_CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Panel_CenterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Panel_Tablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(Panel_Center, java.awt.BorderLayout.CENTER);

        Panel_Left.setPreferredSize(new java.awt.Dimension(400, 650));
        Panel_Left.setLayout(new java.awt.BorderLayout());

        Panel_Information.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Information.setPreferredSize(new java.awt.Dimension(400, 300));
        Panel_Information.setLayout(new javax.swing.BoxLayout(Panel_Information, javax.swing.BoxLayout.PAGE_AXIS));

        Panel_PlayerInfo.setPreferredSize(new java.awt.Dimension(400, 100));
        Panel_PlayerInfo.setRequestFocusEnabled(false);

        Label_Dado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/dado1.png"))); // NOI18N
        jPanel1.add(Label_Dado1);

        Label_Dado2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/dado2.png"))); // NOI18N
        jPanel1.add(Label_Dado2);

        Button_Throw.setText("texto aqui");

        Turno_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Turno_lbl.setText("Es el turno de:");

        NameC_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NameC_lbl.setText("casilla");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Button_Throw)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Turno_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(NameC_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Turno_lbl)
                    .addComponent(Button_Throw))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NameC_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);

        javax.swing.GroupLayout Panel_PlayerInfoLayout = new javax.swing.GroupLayout(Panel_PlayerInfo);
        Panel_PlayerInfo.setLayout(Panel_PlayerInfoLayout);
        Panel_PlayerInfoLayout.setHorizontalGroup(
            Panel_PlayerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        Panel_PlayerInfoLayout.setVerticalGroup(
            Panel_PlayerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_PlayerInfoLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        Panel_Information.add(Panel_PlayerInfo);

        Panel_Players.setPreferredSize(new java.awt.Dimension(400, 250));
        Panel_Players.setLayout(new java.awt.GridLayout(0, 1));

        PanelP1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelP1.setLayout(new java.awt.GridLayout(0, 1));

        NameP1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PanelP1.add(NameP1);

        LastP1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PanelP1.add(LastP1);

        BalP1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PanelP1.add(BalP1);

        Panel_Players.add(PanelP1);

        PanelP2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelP2.setLayout(new java.awt.GridLayout(0, 1));

        NameP2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PanelP2.add(NameP2);

        LastP2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PanelP2.add(LastP2);

        BalP2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PanelP2.add(BalP2);

        Panel_Players.add(PanelP2);

        PanelP3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelP3.setLayout(new java.awt.GridLayout(0, 1));

        NameP3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PanelP3.add(NameP3);

        LastP3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PanelP3.add(LastP3);

        BalP3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PanelP3.add(BalP3);

        Panel_Players.add(PanelP3);

        PanelP4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelP4.setMinimumSize(new java.awt.Dimension(196, 70));
        PanelP4.setPreferredSize(new java.awt.Dimension(196, 70));
        PanelP4.setLayout(new java.awt.GridLayout(0, 1));

        NameP4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NameP4.setText("MAria Perez");
        PanelP4.add(NameP4);

        LastP4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LastP4.setText("Balance 1500");
        PanelP4.add(LastP4);

        BalP4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PanelP4.add(BalP4);

        Panel_Players.add(PanelP4);

        Panel_Information.add(Panel_Players);

        Panel_Left.add(Panel_Information, java.awt.BorderLayout.CENTER);

        Panel_ChatContainer.setBackground(new java.awt.Color(255, 255, 255));
        Panel_ChatContainer.setPreferredSize(new java.awt.Dimension(400, 150));
        Panel_ChatContainer.setLayout(new java.awt.BorderLayout());
        Panel_Left.add(Panel_ChatContainer, java.awt.BorderLayout.SOUTH);

        getContentPane().add(Panel_Left, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JPanel getPanelPlayer(int index){
        if (index == 1){
            return PanelP1;
        }
        else if (index == 2){
            return PanelP2;
        }
        else if (index == 3){
            return PanelP3;
        }
        else if (index == 4){
            return PanelP4;
        }
        return null;
    }
    
    public JLabel getNameC(){
        return NameC_lbl;
    }
    
    public JLabel getNamePlayer(int index){
        if (index == 1){
            return NameP1;
        }
        else if (index == 2){
            return NameP2;
        }
        else if (index == 3){
            return NameP3;
        }
        else if (index == 4){
            return NameP4;
        }
        return null;
    }
    
    public JLabel getLastPLayer(int index){
        if (index == 1){
            return LastP1;
        }
        else if (index == 2){
            return LastP2;
        }
        else if (index == 3){
            return LastP3;
        }
        else if (index == 4){
            return LastP4;
        }
        return null;
    }
    
    public JLabel getBalPlayer(int index){
        if (index == 1){
            return BalP1;
        }
        else if (index == 2){
            return BalP2;
        }
        else if (index == 3){
            return BalP3;
        }
        else if (index == 4){
            return BalP4;
        }
        return null;
    }
    
    public JLabel GetPlayer(){
        return(Playeract);
    }
    
    public JLabel GetTurno(){
        return(Turno_lbl);
    }
    
    public JLabel GetDado1(){
        return(Label_Dado1);
    }
    
    public JLabel GetDado2(){
        return(Label_Dado2);
    }
    
    public JButton GetButton_Throw(){
        return(Button_Throw);
    }
    
    public JLabel GetP1()
    {
        return Label_P1;
    }
    
    public JLabel GetP2()
    {
        return Label_P2;
    }
    
    public JLabel GetP3()
    {
        return Label_P3;
    }
    
    public JLabel GetP4()
    {
        return Label_P4;
    }
    
    public JLabel getPlayerByIndex(int index){
        if (index == 1){
            return Label_P1;
        }
        else if (index == 2){
            return Label_P2;
        }
        else if (index == 3){
            return Label_P3;
        }
        else if (index == 4){
            return Label_P4;
        }
        return null;
    }
    
    public void SetP1Location(int x,int y)
    {
        Label_P1.setLocation(x,y);
    }
    
    public void SetP2Location(int x,int y)
    {
        Label_P2.setLocation(x,y);
    }
    
    public void SetP3Location(int x,int y)
    {
        Label_P3.setLocation(x,y);
    }
    
    public void SetP4Location(int x,int y)
    {
        Label_P4.setLocation(x,y);
    }    
    
    public int GetGox(){
        return(Label_CGO.getX());
    }
    
    public int GetGoy()
    {
        return(Label_CGO.getY());
    }
    
    public int GetFreex(){
        return(Label_CFree.getX());
    }
    public int GetFreey(){
        return(Label_CFree.getY());
    }
    
    public int GetGotox(){
        return(Label_CGoto.getX());
    }
    
    public int GetGotoy(){
        return(Label_CGoto.getY());
    }
    
    public int GetJailx(){
        return(Label_CJail.getX());
    }
    
    public int GetJaily(){
        return(Label_CJail.getY());
    }

    public JPanel getPanel_Tablero() {
        return Panel_Tablero;
    }

    public JPanel getPanel_ChatContainer() {
        return Panel_ChatContainer;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableroView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BalP1;
    private javax.swing.JLabel BalP2;
    private javax.swing.JLabel BalP3;
    private javax.swing.JLabel BalP4;
    private javax.swing.JButton Button_Throw;
    private javax.swing.JPanel Label_CFree;
    private javax.swing.JPanel Label_CGO;
    private javax.swing.JPanel Label_CGoto;
    private javax.swing.JPanel Label_CJail;
    private javax.swing.JLabel Label_Dado1;
    private javax.swing.JLabel Label_Dado2;
    private javax.swing.JLabel Label_P1;
    private javax.swing.JLabel Label_P2;
    private javax.swing.JLabel Label_P3;
    private javax.swing.JLabel Label_P4;
    private javax.swing.JLabel Label_Tablero;
    private javax.swing.JLabel LastP1;
    private javax.swing.JLabel LastP2;
    private javax.swing.JLabel LastP3;
    private javax.swing.JLabel LastP4;
    private javax.swing.JLabel NameC_lbl;
    private javax.swing.JLabel NameP1;
    private javax.swing.JLabel NameP2;
    private javax.swing.JLabel NameP3;
    private javax.swing.JLabel NameP4;
    private javax.swing.JPanel PanelP1;
    private javax.swing.JPanel PanelP2;
    private javax.swing.JPanel PanelP3;
    private javax.swing.JPanel PanelP4;
    private javax.swing.JPanel Panel_Center;
    private javax.swing.JPanel Panel_ChatContainer;
    private javax.swing.JPanel Panel_Information;
    private javax.swing.JPanel Panel_Left;
    private javax.swing.JPanel Panel_PlayerInfo;
    private javax.swing.JPanel Panel_Players;
    private javax.swing.JPanel Panel_Tablero;
    private javax.swing.JLabel Playeract;
    private javax.swing.JLabel Turno_lbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
