/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.TableroViewController;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;


/**
 *
 * @author Ramiro
 */
public class TableroView extends javax.swing.JFrame {
    /**
     * Creates new form TableroView
     */
    public TableroView() {
        initComponents();
        TableroViewController.load(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Center = new javax.swing.JPanel();
        Panel_Tablero = new javax.swing.JPanel();
        Label_P1 = new javax.swing.JLabel();
        Label_P2 = new javax.swing.JLabel();
        Label_P3 = new javax.swing.JLabel();
        Label_P4 = new javax.swing.JLabel();
        Label_Tablero = new javax.swing.JLabel();
        Label_CGO = new javax.swing.JPanel();
        Label_CJail = new javax.swing.JPanel();
        Label_CFree = new javax.swing.JPanel();
        Label_CGoto = new javax.swing.JPanel();
        Panel_Left = new javax.swing.JPanel();
        Button_Throw = new javax.swing.JButton();
        Panel_Dados = new javax.swing.JPanel();
        Label_Dado1 = new javax.swing.JLabel();
        Label_Dado2 = new javax.swing.JLabel();
        Turno_lbl = new javax.swing.JLabel();
        Playeract = new javax.swing.JLabel();
        PanelP1 = new javax.swing.JPanel();
        NameP1 = new javax.swing.JLabel();
        LastP1 = new javax.swing.JLabel();
        BalP1 = new javax.swing.JLabel();
        PanelP2 = new javax.swing.JPanel();
        NameP2 = new javax.swing.JLabel();
        LastP2 = new javax.swing.JLabel();
        BalP2 = new javax.swing.JLabel();
        PanelP3 = new javax.swing.JPanel();
        NameP3 = new javax.swing.JLabel();
        LastP3 = new javax.swing.JLabel();
        BalP3 = new javax.swing.JLabel();
        PanelP4 = new javax.swing.JPanel();
        NameP4 = new javax.swing.JLabel();
        LastP4 = new javax.swing.JLabel();
        BalP4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        Panel_Center.setPreferredSize(new java.awt.Dimension(650, 700));

        Panel_Tablero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Panel_Tablero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_P1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/carr.png"))); // NOI18N
        Panel_Tablero.add(Label_P1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 40, 30));

        Label_P2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/hat.png"))); // NOI18N
        Panel_Tablero.add(Label_P2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 40, 30));

        Label_P3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/dog.png"))); // NOI18N
        Panel_Tablero.add(Label_P3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 40, 30));

        Label_P4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/dedal.png"))); // NOI18N
        Panel_Tablero.add(Label_P4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 30, -1));

        Label_Tablero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tabmonpoly.png"))); // NOI18N
        Panel_Tablero.add(Label_Tablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout Label_CGOLayout = new javax.swing.GroupLayout(Label_CGO);
        Label_CGO.setLayout(Label_CGOLayout);
        Label_CGOLayout.setHorizontalGroup(
            Label_CGOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        Label_CGOLayout.setVerticalGroup(
            Label_CGOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Panel_Tablero.add(Label_CGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 90, 90));

        javax.swing.GroupLayout Label_CJailLayout = new javax.swing.GroupLayout(Label_CJail);
        Label_CJail.setLayout(Label_CJailLayout);
        Label_CJailLayout.setHorizontalGroup(
            Label_CJailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        Label_CJailLayout.setVerticalGroup(
            Label_CJailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Panel_Tablero.add(Label_CJail, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 560, 90, 90));

        javax.swing.GroupLayout Label_CFreeLayout = new javax.swing.GroupLayout(Label_CFree);
        Label_CFree.setLayout(Label_CFreeLayout);
        Label_CFreeLayout.setHorizontalGroup(
            Label_CFreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        Label_CFreeLayout.setVerticalGroup(
            Label_CFreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Panel_Tablero.add(Label_CFree, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 90, 90));

        javax.swing.GroupLayout Label_CGotoLayout = new javax.swing.GroupLayout(Label_CGoto);
        Label_CGoto.setLayout(Label_CGotoLayout);
        Label_CGotoLayout.setHorizontalGroup(
            Label_CGotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        Label_CGotoLayout.setVerticalGroup(
            Label_CGotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        Panel_Tablero.add(Label_CGoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 90));

        javax.swing.GroupLayout Panel_CenterLayout = new javax.swing.GroupLayout(Panel_Center);
        Panel_Center.setLayout(Panel_CenterLayout);
        Panel_CenterLayout.setHorizontalGroup(
            Panel_CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 667, Short.MAX_VALUE)
            .addGroup(Panel_CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Panel_CenterLayout.createSequentialGroup()
                    .addGap(0, 9, Short.MAX_VALUE)
                    .addComponent(Panel_Tablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 8, Short.MAX_VALUE)))
        );
        Panel_CenterLayout.setVerticalGroup(
            Panel_CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(Panel_CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Panel_CenterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Panel_Tablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(Panel_Center, java.awt.BorderLayout.CENTER);

        Panel_Left.setPreferredSize(new java.awt.Dimension(400, 650));

        Button_Throw.setText("texto aqui");

        Label_Dado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/dado1.png"))); // NOI18N
        Panel_Dados.add(Label_Dado1);

        Label_Dado2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/dado2.png"))); // NOI18N
        Panel_Dados.add(Label_Dado2);

        Turno_lbl.setText("Es el turno de:");

        Playeract.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N

        PanelP1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        NameP1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        LastP1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        BalP1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout PanelP1Layout = new javax.swing.GroupLayout(PanelP1);
        PanelP1.setLayout(PanelP1Layout);
        PanelP1Layout.setHorizontalGroup(
            PanelP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelP1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NameP1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                .addComponent(LastP1)
                .addGap(160, 160, 160))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelP1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BalP1)
                .addGap(100, 100, 100))
        );
        PanelP1Layout.setVerticalGroup(
            PanelP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelP1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LastP1)
                    .addComponent(NameP1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BalP1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LastP1.getAccessibleContext().setAccessibleName("");

        PanelP2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        NameP2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        LastP2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        BalP2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout PanelP2Layout = new javax.swing.GroupLayout(PanelP2);
        PanelP2.setLayout(PanelP2Layout);
        PanelP2Layout.setHorizontalGroup(
            PanelP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelP2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NameP2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LastP2)
                .addGap(157, 157, 157))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelP2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BalP2)
                .addGap(104, 104, 104))
        );
        PanelP2Layout.setVerticalGroup(
            PanelP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelP2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LastP2)
                    .addComponent(NameP2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BalP2)
                .addContainerGap())
        );

        PanelP3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        NameP3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        LastP3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        BalP3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout PanelP3Layout = new javax.swing.GroupLayout(PanelP3);
        PanelP3.setLayout(PanelP3Layout);
        PanelP3Layout.setHorizontalGroup(
            PanelP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelP3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NameP3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LastP3)
                .addGap(154, 154, 154))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelP3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BalP3)
                .addGap(105, 105, 105))
        );
        PanelP3Layout.setVerticalGroup(
            PanelP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelP3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LastP3)
                    .addComponent(NameP3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BalP3)
                .addContainerGap())
        );

        PanelP4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        NameP4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        LastP4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        BalP4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout PanelP4Layout = new javax.swing.GroupLayout(PanelP4);
        PanelP4.setLayout(PanelP4Layout);
        PanelP4Layout.setHorizontalGroup(
            PanelP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelP4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NameP4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LastP4)
                .addGap(154, 154, 154))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelP4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BalP4)
                .addGap(108, 108, 108))
        );
        PanelP4Layout.setVerticalGroup(
            PanelP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelP4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LastP4)
                    .addComponent(NameP4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BalP4)
                .addContainerGap())
        );

        javax.swing.GroupLayout Panel_LeftLayout = new javax.swing.GroupLayout(Panel_Left);
        Panel_Left.setLayout(Panel_LeftLayout);
        Panel_LeftLayout.setHorizontalGroup(
            Panel_LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_LeftLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Playeract, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
            .addGroup(Panel_LeftLayout.createSequentialGroup()
                .addGroup(Panel_LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_LeftLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(Button_Throw))
                    .addGroup(Panel_LeftLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(Panel_LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Panel_Dados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Panel_LeftLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(Turno_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_LeftLayout.createSequentialGroup()
                .addGroup(Panel_LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelP4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelP3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelP2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Panel_LeftLayout.setVerticalGroup(
            Panel_LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_LeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Playeract, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(Button_Throw)
                .addGap(18, 18, 18)
                .addComponent(Panel_Dados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Turno_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        getContentPane().add(Panel_Left, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JPanel getPanelPlayer(int index){
        if (index == 1){
            return PanelP1;
        }
        else if (index == 2){
            return PanelP2;
        }
        else if (index == 3){
            return PanelP3;
        }
        else if (index == 4){
            return PanelP4;
        }
        return null;
    }
    
    public JLabel getNamePlayer(int index){
        if (index == 1){
            return NameP1;
        }
        else if (index == 2){
            return NameP2;
        }
        else if (index == 3){
            return NameP3;
        }
        else if (index == 4){
            return NameP4;
        }
        return null;
    }
    
    public JLabel getLastPLayer(int index){
        if (index == 1){
            return LastP1;
        }
        else if (index == 2){
            return LastP2;
        }
        else if (index == 3){
            return LastP3;
        }
        else if (index == 4){
            return LastP4;
        }
        return null;
    }
    
    public JLabel getBalPlayer(int index){
        if (index == 1){
            return BalP1;
        }
        else if (index == 2){
            return BalP2;
        }
        else if (index == 3){
            return BalP3;
        }
        else if (index == 4){
            return BalP4;
        }
        return null;
    }
    
    public JLabel GetPlayer(){
        return(Playeract);
    }
    
    public JLabel GetTurno(){
        return(Turno_lbl);
    }
    
    public JLabel GetDado1(){
        return(Label_Dado1);
    }
    
    public JLabel GetDado2(){
        return(Label_Dado2);
    }
    
    public JButton GetButton_Throw(){
        return(Button_Throw);
    }
    
    public JLabel GetP1()
    {
        return Label_P1;
    }
    
    public JLabel GetP2()
    {
        return Label_P2;
    }
    
    public JLabel GetP3()
    {
        return Label_P3;
    }
    
    public JLabel GetP4()
    {
        return Label_P4;
    }
    
    public JLabel getPlayerByIndex(int index){
        if (index == 1){
            return Label_P1;
        }
        else if (index == 2){
            return Label_P2;
        }
        else if (index == 3){
            return Label_P3;
        }
        else if (index == 4){
            return Label_P4;
        }
        return null;
    }
    
    public void SetP1Location(int x,int y)
    {
        Label_P1.setLocation(x,y);
    }
    
    public void SetP2Location(int x,int y)
    {
        Label_P2.setLocation(x,y);
    }
    
    public void SetP3Location(int x,int y)
    {
        Label_P3.setLocation(x,y);
    }
    
    public void SetP4Location(int x,int y)
    {
        Label_P4.setLocation(x,y);
    }    
    
    public int GetGox(){
        return(Label_CGO.getX());
    }
    
    public int GetGoy()
    {
        return(Label_CGO.getY());
    }
    
    public int GetFreex(){
        return(Label_CFree.getX());
    }
    public int GetFreey(){
        return(Label_CFree.getY());
    }
    
    public int GetGotox(){
        return(Label_CGoto.getX());
    }
    
    public int GetGotoy(){
        return(Label_CGoto.getY());
    }
    
    public int GetJailx(){
        return(Label_CJail.getX());
    }
    
    public int GetJaily(){
        return(Label_CJail.getY());
    }

    public JPanel getPanel_Tablero() {
        return Panel_Tablero;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableroView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BalP1;
    private javax.swing.JLabel BalP2;
    private javax.swing.JLabel BalP3;
    private javax.swing.JLabel BalP4;
    private javax.swing.JButton Button_Throw;
    private javax.swing.JPanel Label_CFree;
    private javax.swing.JPanel Label_CGO;
    private javax.swing.JPanel Label_CGoto;
    private javax.swing.JPanel Label_CJail;
    private javax.swing.JLabel Label_Dado1;
    private javax.swing.JLabel Label_Dado2;
    private javax.swing.JLabel Label_P1;
    private javax.swing.JLabel Label_P2;
    private javax.swing.JLabel Label_P3;
    private javax.swing.JLabel Label_P4;
    private javax.swing.JLabel Label_Tablero;
    private javax.swing.JLabel LastP1;
    private javax.swing.JLabel LastP2;
    private javax.swing.JLabel LastP3;
    private javax.swing.JLabel LastP4;
    private javax.swing.JLabel NameP1;
    private javax.swing.JLabel NameP2;
    private javax.swing.JLabel NameP3;
    private javax.swing.JLabel NameP4;
    private javax.swing.JPanel PanelP1;
    private javax.swing.JPanel PanelP2;
    private javax.swing.JPanel PanelP3;
    private javax.swing.JPanel PanelP4;
    private javax.swing.JPanel Panel_Center;
    private javax.swing.JPanel Panel_Dados;
    private javax.swing.JPanel Panel_Left;
    private javax.swing.JPanel Panel_Tablero;
    private javax.swing.JLabel Playeract;
    private javax.swing.JLabel Turno_lbl;
    // End of variables declaration//GEN-END:variables
}
